CREATE TABLE IF NOT EXISTS `#__settings` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`key` VARCHAR(255)  NOT NULL ,
`value` VARCHAR(255)  NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;

